name : test
on : 
   - push
   - pull_request 
jobs: 
      test:
         runs-on: ubuntu-latest
         steps  : 
            - name : Get code
              uses : actions/checkout@v7
            - name : Install Ptyhon
              uses : actions/setup-python@v6 
              with :
                   python-version : '3.11'
            - name : caching
              uses : actions/cache@v4
              with :
                    path : ~/.cache/pip
                    key  : req-${{ hashFiles('requirements.txt') }}
            - name : intall the requirement packages
              run  : pip install -r requirements.txt 
            - name : test data quaality
              run  : pytest tests/test_data_quality.py 
      build :
        needs : test
        runs-on : ubuntu-latest
        steps : 
            - name : Get code
              uses : actions/checkout@v7
            - name : install python
              uses : actions/setup-python@v6
              with :
                    python-version : '3.11'
            - name : caching
              uses : actions/cache@v4
              with :
                    path : ~/.cache/pip
                    key :  req-${{ hashFiles('requirements.txt') }}
            - name : install requiremnets
              run  : pip install -r requirements.txt
            - name : build Artifact
              run  : python build_output.py
            - name : upload Artifact
              uses : actions/upload-artifact@v4
              with : 
                  name : DataCraft-artifact 
                  path : artifact/*.csv      
      deployment:
          needs   : build
          runs-on : ubuntu-latest
          steps   : 
                - name : Get code
                  uses : actions/checkout@v7
                - name : install python 
                  uses : actions/setup-python@v6
                  with : 
                        python-version :  '3.11'
                - name : caching
                  uses : actions/cache@v4
                  with :
                        path : ~/.cache/pip
                        key :  req-${{ hashFiles('requirements.txt') }}  
                - name : install the requirements
                  run  : pip install -r requirements.txt
                - name : dowenload artifact
                  uses : actions/download-artifact@v4
                  with : 
                        name : DataCraft-artifact
                        path : data/
                - name : list files in data foder
                  run  : | 
                        cd data/
                        ls
                - name : print deploy   
                  run  : echo "deploy"


